using System.Text.RegularExpressions;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Microsoft.AspNetCore.Mvc;

namespace Valuation.Api.Controllers
{
    /// <summary>
    /// Stores PDFs generated by the standalone Vehga report builder so the QR code
    /// printed on the report resolves to the original, unedited file — the same
    /// mechanism ProntoPDFGeneration uses (public-read blob at reports/{ref}.pdf).
    /// </summary>
    [ApiController]
    [Route("api/report-builder")]
    public class ReportBuilderController : ControllerBase
    {
        private static readonly Regex RefPattern = new(@"^[A-Z]{2,3}-\d{6}-[A-Z]$", RegexOptions.Compiled);

        private readonly IConfiguration _config;

        public ReportBuilderController(IConfiguration config) => _config = config;

        // PUT /api/report-builder/reports/PM-123456-A  (body: raw application/pdf)
        [HttpPut("reports/{referenceNumber}")]
        [RequestSizeLimit(100_000_000)]
        public async Task<IActionResult> UploadReportPdf(string referenceNumber)
        {
            referenceNumber = (referenceNumber ?? string.Empty).Trim().ToUpperInvariant();
            if (!RefPattern.IsMatch(referenceNumber))
                return BadRequest(new { message = "Invalid reference number format." });

            var connStr = _config["Blob:ConnectionString"];
            if (string.IsNullOrWhiteSpace(connStr))
                return StatusCode(503, new { message = "Blob storage is not configured." });

            using var ms = new MemoryStream();
            await Request.Body.CopyToAsync(ms);
            if (ms.Length == 0)
                return BadRequest(new { message = "Empty request body — send the PDF bytes." });

            var containerName = _config["Blob:ReportsContainerName"] ?? "reports";
            var container = new BlobContainerClient(connStr, containerName);
            await container.CreateIfNotExistsAsync(PublicAccessType.Blob);

            ms.Position = 0;
            var blob = container.GetBlobClient($"{referenceNumber}.pdf");
            await blob.UploadAsync(ms, new BlobUploadOptions
            {
                HttpHeaders = new BlobHttpHeaders { ContentType = "application/pdf" }
            });

            // Intentionally NOT using Blob:CdnEndpointHostname here — that CDN is scoped to
            // other containers (e.g. "documents") and 404s on "reports". The blob's own Uri
            // is always correct regardless of any CDN in front of other containers.
            return Ok(new { url = blob.Uri.ToString() });
        }
    }
}
