using System.Text;
using System.Text.RegularExpressions;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Microsoft.AspNetCore.Mvc;
using Valuation.Api.Models;
using Valuation.Api.Services;

namespace Valuation.Api.Controllers
{
    /// <summary>
    /// Stores PDFs generated by the standalone Vehga report builder so the QR code
    /// printed on the report resolves to the original, unedited file — the same
    /// mechanism ProntoPDFGeneration uses (public-read blob at reports/{ref}.pdf) — and
    /// the photo gallery beside it that the report's IMAGE LINK opens.
    /// </summary>
    [ApiController]
    [Route("api/report-builder")]
    public class ReportBuilderController : ControllerBase
    {
        private static readonly Regex RefPattern = new(@"^[A-Z]{2,3}-\d{6}-[A-Z]$", RegexOptions.Compiled);

        private readonly IConfiguration _config;

        public ReportBuilderController(IConfiguration config) => _config = config;

        // PUT /api/report-builder/reports/PM-123456-A  (body: raw application/pdf)
        [HttpPut("reports/{referenceNumber}")]
        [RequestSizeLimit(100_000_000)]
        public async Task<IActionResult> UploadReportPdf(string referenceNumber)
        {
            referenceNumber = (referenceNumber ?? string.Empty).Trim().ToUpperInvariant();
            if (!RefPattern.IsMatch(referenceNumber))
                return BadRequest(new { message = "Invalid reference number format." });

            var connStr = _config["Blob:ConnectionString"];
            if (string.IsNullOrWhiteSpace(connStr))
                return StatusCode(503, new { message = "Blob storage is not configured." });

            using var ms = new MemoryStream();
            await Request.Body.CopyToAsync(ms);
            if (ms.Length == 0)
                return BadRequest(new { message = "Empty request body — send the PDF bytes." });

            var containerName = _config["Blob:ReportsContainerName"] ?? "reports";
            var container = new BlobContainerClient(connStr, containerName);
            await container.CreateIfNotExistsAsync(PublicAccessType.Blob);

            ms.Position = 0;
            var blob = container.GetBlobClient($"{referenceNumber}.pdf");
            await blob.UploadAsync(ms, new BlobUploadOptions
            {
                HttpHeaders = new BlobHttpHeaders { ContentType = "application/pdf" }
            });

            // Intentionally NOT using Blob:CdnEndpointHostname here — that CDN is scoped to
            // other containers (e.g. "documents") and 404s on "reports". The blob's own Uri
            // is always correct regardless of any CDN in front of other containers.
            return Ok(new { url = blob.Uri.ToString() });
        }

        // PUT /api/report-builder/reports/PM-123456-A/gallery
        // body: { "registrationNumber": "TS09AB1234", "photos": [ { "label": "FRONT VIEW", "data": "data:image/jpeg;base64,…" } ] }
        //
        // The web gallery the report's IMAGE LINK opens, at reports/{ref}-gallery.html — the
        // page ProntoPDFGeneration publishes beside every portal report. The builder's photos
        // exist only in the browser, so they come with it and are stored in
        // reports/{ref}-gallery/, named per upload so a regenerated report never shows a
        // browser's cached copy of a photo it replaced.
        [HttpPut("reports/{referenceNumber}/gallery")]
        [RequestSizeLimit(100_000_000)]
        public async Task<IActionResult> UploadReportGallery(string referenceNumber, [FromBody] ReportBuilderGalleryRequest request)
        {
            referenceNumber = (referenceNumber ?? string.Empty).Trim().ToUpperInvariant();
            if (!RefPattern.IsMatch(referenceNumber))
                return BadRequest(new { message = "Invalid reference number format." });

            var connStr = _config["Blob:ConnectionString"];
            if (string.IsNullOrWhiteSpace(connStr))
                return StatusCode(503, new { message = "Blob storage is not configured." });

            var sent = request?.Photos ?? new List<ReportBuilderGalleryPhoto>();
            if (sent.Count == 0)
                return BadRequest(new { message = "No photos — send at least one." });
            if (sent.Count > MaxGalleryPhotos)
                return BadRequest(new { message = $"At most {MaxGalleryPhotos} photos." });

            var photos = new List<(string Label, byte[] Bytes, string ContentType, string Extension)>();
            foreach (var p in sent)
            {
                var image = DecodeImage(p.Data);
                if (image == null)
                    return BadRequest(new { message = $"Photo {photos.Count + 1} is not a JPEG, PNG or WebP image." });
                var label = (p.Label ?? string.Empty).Trim();
                photos.Add((label.Length > 60 ? label[..60] : label, image.Value.Bytes, image.Value.ContentType, image.Value.Extension));
            }

            var containerName = _config["Blob:ReportsContainerName"] ?? "reports";
            var container = new BlobContainerClient(connStr, containerName);
            await container.CreateIfNotExistsAsync(PublicAccessType.Blob);

            // Never replace a portal report's gallery. A builder reference can collide with
            // one the portal issued, and this route takes no sign-in.
            var page = container.GetBlobClient($"{referenceNumber}-gallery.html");
            if (await page.ExistsAsync())
            {
                var existing = await page.GetPropertiesAsync();
                if (!existing.Value.Metadata.TryGetValue("source", out var source) || source != BuilderSource)
                    return Conflict(new { message = "That reference already has a portal report's gallery." });
            }

            var folder   = $"{referenceNumber}-gallery/";
            var stamp    = DateTime.UtcNow.ToString("yyyyMMddHHmmss");
            var metadata = new Dictionary<string, string> { ["source"] = BuilderSource };

            var urls = await Task.WhenAll(photos.Select(async (p, i) =>
            {
                var blob = container.GetBlobClient($"{folder}{stamp}-{i + 1:D2}{p.Extension}");
                using var s = new MemoryStream(p.Bytes);
                await blob.UploadAsync(s, new BlobUploadOptions
                {
                    HttpHeaders = new BlobHttpHeaders { ContentType = p.ContentType },
                    Metadata = metadata
                });
                return blob.Uri.ToString();
            }));

            var regNo = (request!.RegistrationNumber ?? string.Empty).Trim();
            if (regNo.Length == 0 || regNo.Length > 30) regNo = referenceNumber;
            var html = ReportGalleryPage.Build(regNo, photos.Select((p, i) => (p.Label, urls[i])));

            using (var hs = new MemoryStream(Encoding.UTF8.GetBytes(html)))
            {
                await page.UploadAsync(hs, new BlobUploadOptions
                {
                    HttpHeaders = new BlobHttpHeaders { ContentType = "text/html; charset=utf-8" },
                    Metadata = metadata
                });
            }

            // The page now points at this upload's photos; the ones it replaced can go.
            await foreach (var old in container.GetBlobsAsync(prefix: folder))
                if (!old.Name.StartsWith($"{folder}{stamp}-", StringComparison.Ordinal))
                    await container.DeleteBlobIfExistsAsync(old.Name);

            return Ok(new { url = page.Uri.ToString(), photos = photos.Count });
        }

        private const string BuilderSource   = "report-builder";
        private const int    MaxGalleryPhotos = 100;
        private const int    MaxPhotoBytes    = 15 * 1024 * 1024;

        /// <summary>
        /// A data URL or bare base64 as image bytes — only if they really are a JPEG, PNG or
        /// WebP. Judged by the bytes, not the type the data URL claims: the page is public.
        /// </summary>
        private static (byte[] Bytes, string ContentType, string Extension)? DecodeImage(string? data)
        {
            if (string.IsNullOrWhiteSpace(data)) return null;
            var comma = data.IndexOf(',');
            var b64 = data.StartsWith("data:", StringComparison.OrdinalIgnoreCase) && comma > 0 ? data[(comma + 1)..] : data;
            if (b64.Length / 4L * 3 > MaxPhotoBytes) return null;

            byte[] bytes;
            try { bytes = Convert.FromBase64String(b64.Trim()); }
            catch (FormatException) { return null; }

            if (bytes.Length > 3 && bytes[0] == 0xFF && bytes[1] == 0xD8 && bytes[2] == 0xFF)
                return (bytes, "image/jpeg", ".jpg");
            if (bytes.Length > 8 && bytes.AsSpan(0, 8).SequenceEqual(new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A }))
                return (bytes, "image/png", ".png");
            if (bytes.Length > 12 && Encoding.ASCII.GetString(bytes, 0, 4) == "RIFF" && Encoding.ASCII.GetString(bytes, 8, 4) == "WEBP")
                return (bytes, "image/webp", ".webp");
            return null;
        }
    }
}
